# Fields to fill out
analyst_name: script_default
site: Akitio at Weber Intersection
from_date: 2024-07-03 13:18:00
to_date: 2025-10-20 14:20

# Hilltop Server Configuration
base_url: http://hilltopdev.horizons.govt.nz/
standard_hts_filename: RawLoggerNet.hts
check_hts_filename: HydrobotCheckData.hts

# Data Source Configuration
data_family: Rainfall
standard_measurement_name: Rainfall [SCADA Rainfall]
check_measurement_name: Check Gauge Total [SCADA Rainfall]
backup_measurement_name: Rainfall (backup) [SCADA Rainfall (backup)]
infer_frequency: false
frequency:

# Export configuration
export_file_name: processed_rf.xml

# Processing Configuration
defaults:
  high_clip: 2.1
  low_clip: -0.1
  max_qc: 600

# Annalist Configuration
logfile: annals_hydrobot.csv
format:
  file: '%(asctime)s, %(analyst_name)s, %(function_name)s, %(site)s, %(measurement)s,
    %(from_date)s, %(to_date)s, %(message)s'
  stream: '%(asctime)s, %(function_name)s'

# Archive hts
archive_base_url: http://hilltopdev.horizons.govt.nz/
archive_standard_hts_filename: Archive.hts
archive_check_hts_filename: Archive.hts
